[env:esp32-c3-devkitm-1]
platform = espressif32 @ 6.7.0
board = esp32-c3-devkitm-1
upload_speed = 115200
upload_flags =
  --no-stub
framework = arduino
monitor_speed = 115200
build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
  adafruit/Adafruit GFX Library @ 1.11.11
  adafruit/Adafruit SH110X @ 2.1.12
  bblanchon/ArduinoJson @ 7.1.0
